### ISSUE TITLE
feat: Course enrollments list API to support the Coruse Details list page

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#108]
We need an API to show student list with information matching the Student list design and the student list CSV for export:

 - https://github.com/Zeit-Labs/dashboard/issues/172

**Target Date:** `2024-10-30`

### Design and Fields

<kbd>![image](https://github.com/user-attachments/assets/2522052b-c0e7-4bbb-bc9c-980f2f61c2b5)</kbd>

**Comment by OmarIthawi** [comment]
Ahmed has been using the normal Student list API which don't have grades or any other course-specific information. It was a hack that needs to be replaced now with a dedicated enrollment-focused API.

**Comment by shadinaif** [comment]
done in https://github.com/nelc/futurex-openedx-extensions/pull/130
