### ISSUE TITLE
feat: Download CSV button changes: sort by most recent first, show progress on list

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#127]
- `progress` field is missing from the list view
 - `sort` isn't supported, it should at least support `sort="-id"` to sort reports to show most recent first

**Comment by tehreem-sadat** [comment]
Progress field is there is tasks list. Sample SS from my local setup.
![image](https://github.com/user-attachments/assets/9a4e5376-fbfd-4216-8d8e-a22e312bd48f)
For sorting, yes we can add that.

**Comment by tehreem-sadat** [comment]
ohh I am sorry I misunderstood, for the view we added ordering at 'created_at' but it's not working. I missed 'filter_backend' in the view. Fixing it.

**Comment by tehreem-sadat** [comment]
@OmarIthawi let me know if anything else is needed to close this issue.

**Comment by OmarIthawi** [comment]
Thanks @tehreem-sadat, clear now.

@amjadsh97 `progress` is available in the list view, would you mind double checking why the frontend isn't using it? Perhaps the TypeScript type system isn't configured correctly?
