### ISSUE TITLE
bug: course_score is being passed as number but in quotes

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#141]
We need to verify this, but it appears that the type is actually a string in the course learners api.

The tests shows it's a string:

https://github.com/nelc/futurex-openedx-extensions/blob/2cc94659c1bee2d2254e1a7e69789849d35326c5/tests/test_dashboard/test_serializers.py#L266

**Comment by shadinaif** [comment]
**Note to myself:** create an issue on dashboard to fix the [related line](https://github.com/Zeit-Labs/dashboard/blob/474202a208f793ed012b3bc2e1530d21f4ac2669/src/app/%5Blocale%5D/%5Btenant%5D/courses/%5BcourseId%5D/learners/CoursestudentsTableClient.tsx#L63) after deploying this fix, and before closing this issue

**Comment by shadinaif** [comment]
issue created for front-end https://github.com/zeit-labs/dashboard/issues/291
