### ISSUE TITLE
bug: Django admin export edit page is very slow on production

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#144]
Open this page in staging or production and it will be very slow:

 - https://lms.futurex.sa/admin/fx_helpers/dataexporttask/8/change/

Please use Search Field for tenant and user Id instead of dropbox because dropbox loads all users (100k+ users).

<kbd>![image](https://github.com/user-attachments/assets/169f99b7-6417-4642-b5fb-cd3302634624)</kbd>

**Comment by shadinaif** [comment]
resolved in https://github.com/nelc/futurex-openedx-extensions/pull/149

**Comment by OmarIthawi** [comment]
yes indeed, thank you so much :)
