### ISSUE TITLE
feat: save dhaboard files on a different S3 bucket

### ISSUE THREAD

**Issue by shadinaif** [nelc/futurex-openedx-extensions#153]
Download URLs for dashboard exported files are signed (on staging for now). But we have a problem: the bucket containing them (the default bucket) allows public access. It means that the user can simply use the URL without the signature info and still access the file normally

**How to resolve this?**

We need to move the data to another bucket. We can create a new bucket for dashboard data

I [Shadi] thought we could use the special ORA2 bucket defined in `FILE_UPLOAD_STORAGE_BUCKET_NAME` settings. But I found that it's also flat and not protected 🫤 

This will require a small tweak in the report upload code

**Comment by OmarIthawi** [comment]
@shadinaif the upload code can specificy object (file) specific permissions.

So this shouldn't be an issue in-my-opinion and we can use the same bucket:

 - https://bluexp.netapp.com/blog/aws-cvo-blg-s3-access-for-objects-with-different-permissions-in-an-s3-bucket

The bucket permission is the default permission for all objects, as far as I know. The default, can be overridden on a per-object basis.

**Comment by OmarIthawi** [comment]
@tehreem-sadat @shadinaif the upload code can specificy object (file) specific permissions.

So this shouldn't be an issue in-my-opinion and we can use the same bucket:

https://bluexp.netapp.com/blog/aws-cvo-blg-s3-access-for-objects-with-different-permissions-in-an-s3-bucket
The bucket permission is the default permission for all objects, as far as I know. The default, can be overridden on a per-object basis.
