### ISSUE TITLE
chore: Share Mobile APIs commits on nelc/edx-platform with Andrey 

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#162]
**Due Date:** `12-12-2024`

I've cherry-picked many mobile API commits from Redwood and Sumac releases in the following two PRs:

 - https://github.com/nelc/edx-platform/pull/34
 - https://github.com/nelc/edx-platform/pull/29

Each PR contains many commits. Most of them are from Redwood, so they need no work.

However, some of those PRs are in Sumac only and needs to be cherry-picked again by Andrey and Johan into NeLC's Redwood branch.

Kindly check those pull requests and share the Sumac commits with Andrey either on Slack or in the following doucment:

 - https://docs.google.com/spreadsheets/d/1MB97ieTmUdyyte9elBcHub4D7lsrcaKe0kN6WDRN0WI/edit?pli=1&gid=2137479809#gid=2137479809

**Comment by tehreem-sadat** [comment]
@shadinaif  I ran following command to get all the commits that are on sumac and not on redwood:

`git log origin/open-release/redwood.master..origin/open-release/sumac.master --oneline -- lms/djangoapps/mobile_api`

```
8ddc58283f Merge pull request #34859 from raccoongang/kireiev/AXM-549/feat/upstream_PR_active_inactive_courses_API
13e3024ae3 style: [FC-0047] fix code style issues
9a0734b280 style: [FC-0047] add module docstrings
28eb406f8d feat: [FC-0047] add settings for edx-ace push notifications
b77b90a344 fix: Enable courseware access api for all types of course(expired, cl… (#35155)
3589d964cb feat: Added mobile api for course enrollment and other details. (#35100)
53174178f3 feat: [FC-0047] Extend mobile API with course progress and primary courses on dashboard view (#34848)
11626148d9 refactor: switch from mock to unittest.mock (#34844)
```
Afterwards, I reviewed the commits listed in the PRs shared by Omar, and found only one commit that is present in **sumac**, but not in **redwood**, and is also mentioned in the PRs shared by Omar.

**Comment by OmarIthawi** [comment]
Thanks @tehreem-sadat and @shadinaif.

Information was sent to the team. Closing this as done.
