### ISSUE TITLE
perf: Student details page is somewhat slow

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#21]
The API is ~~really~~ somewhat slow, it takes ~~18~~ 9 seconds to load.

Open this page and observe:

 - https://dashboard.futurex.sa/ar/121/students/Abdullah

My understanding that frontend is performing okay and it's a backend fault, but we can double check.

Edit: After using the `tenant_ids` parameter, the page loads faster with correct data.

cc: @iamjazzar

**Comment by shadinaif** [comment]
let's test if [v0.3.6](https://github.com/nelc/futurex-openedx-extensions/releases/tag/v0.3.6) resolved it

**Comment by shadinaif** [comment]
latest v0.8.13 resolved it
