### ISSUE TITLE
feat: Add a role management API for both courses and organization-wide roles

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#22]
Faris will provide us with a design so we make the API for.

But generally the API should allow the following:

```
GET /roles
user_id:
```

```
POST /roles
org: (double checked for secuirty reasons)
course_id: (optional, if we need a course-specific role)
user_ids: ['test@example', 'username123'] (multiple users at once)
```

```
DELETE /roles
By role ID
```

```
DELETE /roles
by user ID
```

---------

Supported roles:

- Site Staff (مدير الموقع)
- Site Instructor (طاقم الموقع)
- Course Community TA (مساعد أستاذ لشؤون المتعلّمين في المقرر)
- Course Group Community TA (مساعد مدرس لمجموعة المنتدى)
- Course Discussion Moderators (مشرفو منتدى نقاش المقرر)
- Course Data Researcher (باحث بيانات المقرر)
- Course Discussion Admins (مشرفو نقاشات المقرر)
- Course Beta Testers (مختبرو نسخة المقرر التجريبية)
- Course Staff (مشرف المقرر)
- Course Instructor (طاقم المقرر)
- Course Creator Role (منشيء مقررات)

Notes about roles:
 - Staff vs Instructor: Staff can add/remove instructors, but not the other way around.
 - Course-specific and org-wide roles are the same but the difference is the `course_id` property is null for org-wide roles.

**Comment by shadinaif** [comment]
closing in favor of https://github.com/nelc/futurex-openedx-extensions/issues/61
