### ISSUE TITLE
fix: Whitelist all `https://dashboard.stage.nelp.gov.sa/` for login redirects

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#39]
Please check this PR and ensure it's working fine: https://github.com/nelc/manifest-sagar/pull/397

**Comment by OmarIthawi** [comment]
@iamjazzar fyi it should be whitelisted:

```
$ ./manage.py lms print_setting LOGIN_REDIRECT_WHITELIST

['studio.stage.nelp.gov.sa', 'dashboard.stage.nelp.gov.sa', 'stage.nelp.gov.sa']
```

@iamjazzar please close this bug until we fix the redirect end to end.

**Comment by shadinaif** [comment]
Closing because @iamjazzar and @OmarIthawi resolved this issue
