### ISSUE TITLE
feat: API to show the current user permissions

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#40]
This is mostly need to be used for UX purposes to, for example, hide specific areas:

 - Tenant-wide stats cards
 - Studio button for data reseachers

**Comment by OmarIthawi** [comment]
@shadinaif this is mostly relavant to my other comment here:

 - https://github.com/nelc/futurex-openedx-extensions/pull/77#discussion_r1778658599

cc: @tehreem-sadat

**Comment by shadinaif** [comment]
Implemented by https://github.com/nelc/futurex-openedx-extensions/pull/93
