### ISSUE TITLE
api bug: numbers and permissions are a bit odd on the tenant ID 100

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#41]
### Bugs
 - Students show 0 courses, which makes no sense
 - Student details page, lists no coureses

### Screenshot
![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/75a757ed-99b9-43fa-8e64-0c6bc2354292)

**Comment by shadinaif** [comment]
Fixed
