### ISSUE TITLE
bug: one course shows up as a number but no list is shown for user

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#46]
Link has been shared on Slack for privacy:

 - https://zeit-labs.slack.com/archives/C05JZU90L0M/p1720076163358249

### Details page
![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/0f1ad57f-5327-4fa8-b99d-fbb65fe886c5)

### Student list (last record)
![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/a7886dad-89b1-4d46-bd33-a5e3ecbb7dd9)

**Comment by shadinaif** [comment]
resolved in https://github.com/nelc/futurex-openedx-extensions/pull/48
