### ISSUE TITLE
bug: اذا كان لدى المتعلم مقررات من مواقع اخرى تظهر ايضا

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#50]
@shadinaif This bug has been reported without additional context. I'll reach out to Ali for further details.

**Bug:** Courses from other sites appear in the learner details page. This seems like an API issue.

**Comment by shadinaif** [comment]
I tried a lot, and could not reproduce. Code trace shows it's not possible. A real sample will help a lot!

**Comment by OmarIthawi** [comment]
Yes, I'm thinking it's a mobile app issue!

**Comment by OmarIthawi** [comment]
Closed: cannot reproduce.
