### ISSUE TITLE
bug: Numbers are different between different APIs

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#65]
Numbers are different between different APIs.

![image](https://github.com/user-attachments/assets/55baf207-dbaf-4d1b-a138-84cc983cdd73)

**Comment by OmarIthawi** [comment]
Same on production: https://dashboard.futurex.sa/ar/121/students

![image](https://github.com/user-attachments/assets/feb2a5cb-6bd0-4d4a-9455-f47436b949a8)

![image](https://github.com/user-attachments/assets/a9785944-56f0-47be-8b94-800327a406cb)

**Comment by shadinaif** [comment]
Fixed by https://github.com/nelc/futurex-openedx-extensions/pull/74
