### ISSUE TITLE
bug: SREI production instance shows all courses count even if they're for testing purposes

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#7]
Go to https://dashboard.futurex.sa/ and check SREI course results

Actual result: 17
Expected result: 3 (or anything other than 17)

![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/27aecaad-9145-4c68-9b57-e38bfa6628a5)

**Comment by shadinaif** [comment]
thank you @OmarIthawi . For now, I'll exclude all courses with `catalog_visibility not in ('about', 'both')`. That will make the value 4 (three `active` and one `ended`). Do you think we need a global filter in the dashboard to include/exclude hidden courses? like a checkbox somewhere on the page (not a settings,,, settings will be confusing and hard to find)

**Comment by OmarIthawi** [comment]
> thank you @OmarIthawi . For now, I'll exclude all courses with `catalog_visibility not in ('about', 'both')`. That will make the value 4 (three `active` and one `ended`). Do you think we need a global filter in the dashboard to include/exclude hidden courses? like a checkbox somewhere on the page (not a settings,,, settings will be confusing and hard to find)

I think we should have as few settings as possible.

Your suggestion works regarding `catelog_visibility`.

**Comment by OmarIthawi** [comment]
@shadinaif kindly keep this issue open until it's closed in production. Last time I checked it's still an issue for SREI in https://dashboard.futurex.sa/ .
