### ISSUE TITLE
bug: UserSignupSource for users with roles

### ISSUE THREAD

**Issue by shadinaif** [nelc/futurex-openedx-extensions#91]
When an API is called with `include_staff=1`; the staff user will not be included in the result unless the `UserSignupSource` is correctly filled. We must check if that record is being automatically added; and fix it if it's not

**Comment by OmarIthawi** [comment]
@shadinaif UserSignupSource is not added for course or tenant-wide staff users as far as I know.

It's only added in two cases:

  - Register from the site
  - Enroll in a course on that site

**Comment by shadinaif** [comment]
Fixed in: https://github.com/nelc/futurex-openedx-extensions/pull/100

we need to run a small script to loop on all users with roles to fix the data issue
