### ISSUE TITLE
bug: certificate button is not showing for learners with 3 certificates

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-openedx-extensions#96]
- Go to the following URL: https://dashboard.futurex.sa/ar/121/students
- Search for the learner `sad5497`
- His account shows 2 certs: 
  <kbd>![image](https://github.com/user-attachments/assets/8d6c628c-2302-4917-b907-f335949b8d71)</kbd>
- The course detilas shows no certificate links: 
  <kbd>![image](https://github.com/user-attachments/assets/f7fcf750-a23f-4b89-bfca-f550a0eb7297)</kbd>

The two resutls should be consistent.

**Comment by shadinaif** [comment]
Fixed by https://github.com/nelc/futurex-openedx-extensions/pull/98
